### PR TITLE
Make extraction safer

### PR DESCRIPTION
**Pull request by thommay**
* optionally ignore file permissions in the archive
* optionally ignore certain paths in the archive

### CODE REVIEW

**Comment by thommay** [comment]
@lamont-granquist

**Comment by Tensibai** [comment]
Dropping this here as related: would it worth managing owner and group too (in name/numeric fashion as can do `tar`) or is it out of scope for this library ?

**Comment by thommay** [comment]
I'd certainly be open to taking a PR for that should someone need it - say for doing a tar resource or similar.

**Comment by lamont-granquist** [comment]
👍 

yeah i wondered about owner/group, but i haven't seen the use case for it yet

**Comment by Tensibai** [comment]
@lamont-granquist I can't see one out of restoring a backup (which shouldn't be done in ruby IMHO), and si I'm really unsure the feature worth the extra complexity.

I did asked as it sounded obvious to talk about it after this change, but I don't think this library should be a `tar` clone in ruby.

**Pull request merged**
